добавил фильтрацию и сортировку
htmlacademy-ecmascript/1138711-cinemaddict-13 pull request #14
Opened 2021-01-06 10:19 UTC by Yougn

2021-01-06 10:49 UTC, balesniy commented on src/presenter/movie-presenter.js
>      films.addEventListener(`click`, (evt) => {
эти обработчики копятся на элементе при каждой смене данных

2021-01-13 08:10 UTC, balesniy requested changes

2021-01-13 08:10 UTC, balesniy commented on src/model/cards.js
>        update,
это лишнее, добавляет карточку в комменты

2021-01-13 08:10 UTC, balesniy commented on src/presenter/filmDetails.js
> +export default class FilmDetailsPresenter {
файл нужно назвать по схеме из критерия

2021-01-13 08:10 UTC, balesniy commented on src/presenter/filmDetails.js
> +    if (prevfilmDetailsComponent === null) {
лишняя проверка, компонент выше создается, нам нужно проверять наличие готового компонента, см пример в учебном

2021-01-13 08:10 UTC, balesniy commented on src/presenter/filmDetails.js
> +    films.removeEventListener(`click`, (evt) => {
анонимный обработчик не удаляется

2021-01-13 08:10 UTC, balesniy commented on src/presenter/movies.js
> +    this._currentPopUp = {};
в конструктор лучше поставить null чтобы удобно проверять наличие

2021-01-13 08:10 UTC, balesniy commented on src/presenter/movies.js
>      films.addEventListener(`click`, (evt) => {
анонимный обработчик будет не снять

2021-01-13 08:10 UTC, balesniy commented on src/presenter/movies.js
тут просится тернарный оператор

2021-01-13 08:10 UTC, balesniy commented on src/view/film-details.js
> +    const commentsCopy = this._data.comments.slice();
массивы нужно назвать во множественном числе

2021-01-13 08:10 UTC, balesniy commented on src/view/film-details.js
> +    this._callback.addClick = callback;
в названии колбэка лишний "клик"

2021-01-13 08:10 UTC, balesniy commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
обработчики событий просят поставить "внизу"

2021-01-13 08:11 UTC, merged

2021-01-13 11:05 UTC, Yougn commented on src/model/cards.js
>        update,
Исправлено

2021-01-13 11:10 UTC, Yougn commented on package.json
> +    "dayjs": "^1.9.5",
Исправлено

2021-01-13 11:31 UTC, Yougn commented on src/presenter/filmDetails.js
> +export default class FilmDetailsPresenter {
Исправлено

2021-01-13 11:35 UTC, Yougn commented on src/presenter/movie-presenter.js
>      films.addEventListener(`click`, (evt) => {
Исправлено

2021-01-13 11:41 UTC, Yougn commented on src/presenter/filmDetails.js
> +    if (prevfilmDetailsComponent === null) {
Исправлено

2021-01-13 12:08 UTC, Yougn commented on src/presenter/movies.js
> +    this._currentPopUp = {};
Исправлено

2021-01-13 12:08 UTC, Yougn commented on src/presenter/filmDetails.js
> +    films.removeEventListener(`click`, (evt) => {
Исправлено

2021-01-13 12:09 UTC, Yougn commented on src/presenter/movies.js
>      films.addEventListener(`click`, (evt) => {
Исправлено

2021-01-13 12:12 UTC, Yougn commented on src/view/film-details.js
> +    const commentsCopy = this._data.comments.slice();
Исправлено

2021-01-13 12:19 UTC, Yougn commented on src/view/film-details.js
> +    this._callback.addClick = callback;
Исправлено

2021-01-13 12:20 UTC, Yougn commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
Исправлено

2021-01-13 12:22 UTC, Yougn commented on src/view/sort.js
> +  _sortTypeChangeHandler(evt) {
Исправлено