подключил сервер
htmlacademy-ecmascript/1138711-cinemaddict-13 pull request #17
Opened 2021-01-23 22:16 UTC by Yougn

2021-01-27 13:37 UTC, balesniy requested changes

2021-01-27 13:37 UTC, balesniy commented on src/api.js
> +  deleteComment(card) {
лучше передавать параметром сам id коммента, не записывая его в карточку

2021-01-27 13:37 UTC, balesniy commented on src/main.js
> +    cardsModel.setCards(UpdateType.INIT, []);
повторяется код в ветках

2021-01-27 13:37 UTC, balesniy commented on src/mock/cards.js
> +    // genres: generateGenres(),
моки нам больше не нужны, можно убирать из проекта

2021-01-27 13:37 UTC, balesniy commented on src/view/film-details.js
>      commentsCopy.splice(currentComment, 1);
удалять комментарий нужно только после успешного ответа сервера, в обработчике мы вызываем колбэк commentId, дальше ждем апи, после этого обновляем модель и только потом вьюшку

2021-01-27 13:37 UTC, balesniy commented on src/view/film-details.js
>      commentsCopies.push(newComment);
так же и с добавлением, только после ответа сервера новые данные должны попадать в модель, напрямую во вьюшке мы не трогаем данные, только вызываем колбэки, чтобы запросить данные у сервера

2021-01-27 13:37 UTC, balesniy commented on src/view/statistics.js
> +          this.updateData({
повторяется код в ветках

2021-01-27 15:13 UTC, Yougn commented on src/api.js
> +  deleteComment(card) {
Исправлено

2021-01-27 15:17 UTC, Yougn commented on src/main.js
> +    cardsModel.setCards(UpdateType.INIT, []);
Исправлено

2021-01-27 15:19 UTC, Yougn commented on src/mock/cards.js
> +    // genres: generateGenres(),
решил оставить, могут мне еще пригодиться

2021-01-27 15:41 UTC, Yougn commented on src/view/statistics.js
> +          this.updateData({
Исправлено

2021-01-27 17:00 UTC, Yougn commented on src/view/film-details.js
>      commentsCopies.push(newComment);
Исправлено

2021-01-31 23:27 UTC, balesniy requested changes

2021-01-31 23:27 UTC, balesniy commented on src/view/film-details.js
> +    <p class="film-details__comment-text">${comment.comment.length > SpecialName.SYMBOLS_COUNT ? comment.comment.slice(0, SpecialName.SYMBOLS_COUNT) + `...` : comment.comment }</p>
это лишнее, текст нужно показать полностью

2021-01-31 23:27 UTC, balesniy commented on src/view/film-details.js
> +        ${isDeleting ? `Deleting...` : `Delete`}
тут можно сравнивать id кнопки и менять на ней надпись при удалении

2021-01-31 23:27 UTC, balesniy commented on src/view/film-details.js
> +    const commentEmotion = this._data.currentEmoji;
тут нужна проверка, что текст добавлен и эмоция выбрана

2021-01-31 23:27 UTC, balesniy commented on src/view/statistics.js
> +    let changePeriod = (DaysNumbers, Periods) => {
тут лишние заглавные и нужен const

2021-02-01 06:23 UTC, Yougn commented on src/view/statistics.js
> +    let changePeriod = (DaysNumbers, Periods) => {
Исправлено

2021-02-01 06:30 UTC, Yougn commented on src/view/film-details.js
> +    const commentEmotion = this._data.currentEmoji;
Исправлено

2021-02-01 06:34 UTC, Yougn commented on src/view/film-details.js
> +        ${isDeleting ? `Deleting...` : `Delete`}
не понял с чем id сравнивать. в этом случае использую id чтобы передать  наверх в презентер и там изменить флаг. в шаблон никакие id не приходят

2021-02-01 06:35 UTC, Yougn commented on src/view/film-details.js
> +    <p class="film-details__comment-text">${comment.comment.length > SpecialName.SYMBOLS_COUNT ? comment.comment.slice(0, SpecialName.SYMBOLS_COUNT) + `...` : comment.comment }</p>
Исправлено, п 1.3 критерий

2021-02-01 06:37 UTC, Yougn commented on src/presenter/movies-presenter.js
> +    resetSortType ? this._currentSortType = SortType.DEFAULT : ` `;
Исправлено, но в предыдущей редакции код понятней

2021-02-01 06:37 UTC, Yougn commented on src/presenter/movies-presenter.js
> +    for (let i = 0; i < 2; i++) {
Исправлено

2021-02-01 06:47 UTC, balesniy commented on src/view/film-details.js
> +        ${isDeleting ? `Deleting...` : `Delete`}
да, сейчас они до шаблона не доходят, презентер напрямую меняет разметку, см. коммент про это

2021-02-01 06:49 UTC, balesniy commented on src/presenter/movies-presenter.js
> +    resetSortType ? this._currentSortType = SortType.DEFAULT : ` `;
в такой редакции код нерабочий, тогда уж вернуть if- else если тернарный пугает

2021-02-01 06:51 UTC, Yougn commented on src/presenter/movies-presenter.js
> +    switch (actionType) {
Исправлено

2021-02-01 06:55 UTC, Yougn commented on src/view/film-details.js
> +        ${isDeleting ? `Deleting...` : `Delete`}
Исправлено

2021-02-01 06:55 UTC, Yougn commented on src/presenter/movies-presenter.js
> +    resetSortType ? this._currentSortType = SortType.DEFAULT : ` `;
Исправлено

2021-02-01 07:01 UTC, Yougn commented on src/presenter/filmDetails-presenter.js
> +    this.setStateForm(State.DELETING);
Исправлено

2021-02-01 07:16 UTC, Yougn commented on src/presenter/filmDetails-presenter.js
> +    const deleteBtn = document.getElementById(commentId);
Исправлено

2021-02-01 14:00 UTC, balesniy approved these changes

2021-02-01 14:00 UTC, merged

2021-02-01 14:37 UTC, Yougn commented on src/presenter/filmDetails-presenter.js
>  export default class FilmDetailsPresenter {
Исправлено

2021-02-01 14:38 UTC, Yougn commented on src/presenter/movies-presenter.js
> +    if (filtrRatedCards) {
Исправлено