Создал моковые данные
htmlacademy-ecmascript/1138711-cinemaddict-13 pull request #5
Opened 2020-11-26 14:23 UTC by Yougn

2020-11-27 07:47 UTC, balesniy requested changes

2020-11-27 07:47 UTC, balesniy commented on package.json
> +    "dayjs": "^1.9.5"
версии зависимостей просят фиксировать

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +const getRandomInteger = (a = 0, b = 1) => {
параметрам нужно дать более наглядные названия

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const titles = [
это похоже на константу

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const poster = './images/posters/' + images[randomIndex];
повторяется код получения случайного элемента массива, имеет смысл оформить функцию

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const descriptions = [
константа

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const maxNumber = 5;
константы

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  var rand = min + Math.random() * (max + 1 - min);
getRandomInteger + сокращение в названии

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  let minutes = mins % 60;
const

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  var duration = require('dayjs/plugin/duration');
это ой

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const maxDuration = 180;
константы

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +  const countrys = [
константа

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +    actors: generateAuthor(),
актеры и авторы

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +    comments,
тут нужен массив комментов

2020-11-27 07:47 UTC, balesniy commented on src/mock/card.js
> +    ageRating: generateAgeRating()
еще нужны  флаги избранного и др

2020-11-27 07:47 UTC, balesniy commented on src/view/film-details.js
> +                <span class="film-details__genre">${genre}</span>
жанры должны быть в массиве

2020-11-27 07:47 UTC, balesniy commented on src/view/film-details.js
>          <ul class="film-details__comments-list">
список коментов нужно отрисовать из массива

2020-11-27 10:37 UTC, Yougn commented on package.json
> +    "dayjs": "^1.9.5"
Исправлено

2020-11-27 10:39 UTC, Yougn commented on src/mock/card.js
> +const getRandomInteger = (a = 0, b = 1) => {
Исправлено

2020-11-27 10:46 UTC, Yougn commented on src/mock/card.js
> +  const titles = [
Исправлено

2020-11-27 11:04 UTC, Yougn commented on src/mock/card.js
> +  const poster = './images/posters/' + images[randomIndex];
Исправлено

2020-11-27 11:05 UTC, Yougn commented on src/mock/card.js
> +  const descriptions = [
Исправлено

2020-11-27 11:34 UTC, Yougn commented on src/mock/card.js
> +  const maxNumber = 5;
Исправлено

2020-11-27 11:47 UTC, Yougn commented on src/mock/card.js
> +  var rand = min + Math.random() * (max + 1 - min);
Исправлено

2020-11-27 11:48 UTC, Yougn commented on src/mock/card.js
> +  let minutes = mins % 60;
Исправлено

2020-11-27 11:50 UTC, Yougn commented on src/mock/card.js
> +  const maxDuration = 180;
Исправлено

2020-11-27 11:51 UTC, Yougn commented on src/mock/card.js
> +  const countrys = [
Исправлено

2020-11-27 11:53 UTC, Yougn commented on src/mock/card.js
> +    actors: generateAuthor(),
Исправлено

2020-11-27 11:59 UTC, Yougn commented on src/mock/card.js
> +  var duration = require('dayjs/plugin/duration');
Исправлено

2020-11-27 12:14 UTC, Yougn commented on src/mock/card.js
> +    comments,
Исправлено

2020-11-30 12:14 UTC, Yougn commented on src/mock/card.js
> +    ageRating: generateAgeRating()
Исправлено

2020-11-30 12:53 UTC, Yougn commented on src/view/film-details.js
> +                <span class="film-details__genre">${genre}</span>
Исправлено

2020-11-30 13:08 UTC, Yougn commented on src/view/film-details.js
>          <ul class="film-details__comments-list">
Исправлено

2020-12-02 06:13 UTC, balesniy requested changes

2020-12-02 06:13 UTC, balesniy commented on src/main.js
>  render(siteHeader, createProfileContent(), `beforeend`);
способ добавления нужно оформить в константы, имеет смысл beforeend поставить по-умолчанию

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  const images = [`made-for-each-other.png`, `popeye-meets-sinbad.png`,
константы нужно оформить капсом и вынести из функции

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +    descriptionFilms.push(descriptions[randomIndex]);
для получения случайного набора randomIndex нужно вычислить в цикле

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  return parseFloat(rand.toFixed(1));
rand.toFixed лишний если переводим в число

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  const duration = require(`dayjs/plugin/duration`);
'require' is not defined

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  const maxDaysGap = 360;
константа

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +    count: getRandomInteger(0, COMMENT_COUNT),
count для отдельного коммента не нужен

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  for (let i = 0; i < NUMBER; i++) {
нам нужно взять случайное количество комментариев

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +  for (let i = 0; i <= genreLists.length; i++) {
i <= genreLists.length добавит элемент за пределами длины массива

2020-12-02 06:13 UTC, balesniy commented on src/mock/cards.js
> +    films: getRandomInteger(MIN_FILMS, MAX_FILMS),
films для отдельного фильма лишний

2020-12-02 06:13 UTC, balesniy commented on src/mock/filtration.js
> +    .filter((card) => card.isWatched).length,
чтобы избавиться от множественных циклов можно применить reduce

2020-12-02 06:13 UTC, balesniy commented on src/view/footer-statistics.js
> +export const createFooterStatistics = (card) => {
названию параметра нужно жать более наглядное имя

2020-12-02 10:51 UTC, Yougn commented on src/mock/cards.js
> +  const images = [`made-for-each-other.png`, `popeye-meets-sinbad.png`,
Исправлено

2020-12-02 10:52 UTC, Yougn commented on src/mock/cards.js
> +    descriptionFilms.push(descriptions[randomIndex]);
Исправлено

2020-12-02 10:57 UTC, Yougn commented on src/mock/cards.js
> +  return parseFloat(rand.toFixed(1));
Исправлено. Использовал только метод .toFixed()

2020-12-02 10:59 UTC, Yougn commented on src/mock/cards.js
> +  const duration = require(`dayjs/plugin/duration`);
Исправлено

2020-12-02 11:00 UTC, Yougn commented on src/mock/cards.js
> +  const maxDaysGap = 360;
Исправлено

2020-12-02 11:01 UTC, Yougn commented on src/mock/cards.js
> +    count: getRandomInteger(0, COMMENT_COUNT),
Исправлено

2020-12-02 11:07 UTC, Yougn commented on src/mock/cards.js
> +  for (let i = 0; i < NUMBER; i++) {
Исправлено

2020-12-02 11:16 UTC, Yougn commented on src/mock/cards.js
> +  for (let i = 0; i <= genreLists.length; i++) {
Исправлено

2020-12-02 11:21 UTC, Yougn commented on src/mock/cards.js
> +    films: getRandomInteger(MIN_FILMS, MAX_FILMS),
Исправлено

2020-12-02 11:31 UTC, Yougn commented on src/view/footer-statistics.js
> +export const createFooterStatistics = (card) => {
Исправлено

2020-12-02 12:02 UTC, Yougn commented on src/main.js
>  render(siteHeader, createProfileContent(), `beforeend`);
Исправлено

2020-12-02 12:45 UTC, merged