добавил заглушку
htmlacademy-ecmascript/1138711-cinemaddict-13 pull request #7
Opened 2020-12-05 19:56 UTC by Yougn

2020-12-06 10:54 UTC, balesniy requested changes

2020-12-06 10:54 UTC, balesniy commented on src/main.js
> +const BODY = document.querySelector(`body`);
тут лишний капс

2020-12-06 10:54 UTC, balesniy commented on src/main.js
> +const siteMainElement = document.querySelector(`.main`);
посмотри на https://up.htmlacademy.ru/ecmascript/13/criteries#b14

2020-12-06 10:54 UTC, balesniy commented on src/main.js
> +  const popUpFilmDetails = document.querySelector(`.film-details`);
тут лишний поиск по селектору получился, элемент можно взять из компонента

2020-12-06 10:54 UTC, balesniy commented on src/main.js
> +    popUpFilmDetails.remove();
еще нужно обработчик с документа удалить

2020-12-07 11:31 UTC, Yougn commented on src/main.js
> +const BODY = document.querySelector(`body`);
Исправлено

2020-12-07 11:35 UTC, Yougn commented on src/main.js
> +const siteMainElement = document.querySelector(`.main`);
Исправлено

2020-12-07 11:39 UTC, Yougn commented on src/main.js
> +  const popUpFilmDetails = document.querySelector(`.film-details`);
Исправлено

2020-12-07 11:42 UTC, Yougn commented on src/main.js
> +    popUpFilmDetails.remove();
Исправлено

2020-12-08 14:33 UTC, balesniy commented on src/main.js
> +  const popUp = new FilmDetails(cards[0]);
карточку нужно передать параметром в функцию, чтобы отрисовывать актуальные данные

2020-12-08 14:34 UTC, merged